/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBoardRouteImport } from './routes/_app/board'
import { Route as AppFilesRouteImport } from './routes/_app/files'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppWebRouteImport } from './routes/_app/web'
import { Route as AppFilesDocIdRouteImport } from './routes/_app/files.$docId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppWebRoute = AppWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesDocIdRoute = AppFilesDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => AppFilesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/board': typeof AppBoardRoute
  '/files': typeof AppFilesRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/web': typeof AppWebRoute
  '/files/$docId': typeof AppFilesDocIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/board': typeof AppBoardRoute
  '/files': typeof AppFilesRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/web': typeof AppWebRoute
  '/': typeof AppIndexRoute
  '/files/$docId': typeof AppFilesDocIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/board': typeof AppBoardRoute
  '/_app/files': typeof AppFilesRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/web': typeof AppWebRoute
  '/_app/': typeof AppIndexRoute
  '/_app/files/$docId': typeof AppFilesDocIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/board'
    | '/files'
    | '/reports'
    | '/web'
    | '/files/$docId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/board'
    | '/files'
    | '/reports'
    | '/web'
    | '/'
    | '/files/$docId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/board'
    | '/_app/files'
    | '/_app/reports'
    | '/_app/web'
    | '/_app/'
    | '/_app/files/$docId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board': {
      id: '/_app/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/web': {
      id: '/_app/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof AppWebRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files/$docId': {
      id: '/_app/files/$docId'
      path: '/$docId'
      fullPath: '/files/$docId'
      preLoaderRoute: typeof AppFilesDocIdRouteImport
      parentRoute: typeof AppFilesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppFilesRouteChildren {
  AppFilesDocIdRoute: typeof AppFilesDocIdRoute
}

const AppFilesRouteChildren: AppFilesRouteChildren = {
  AppFilesDocIdRoute: AppFilesDocIdRoute,
}

const AppFilesRouteWithChildren = AppFilesRoute._addFileChildren(
  AppFilesRouteChildren,
)

interface AppRouteChildren {
  AppBoardRoute: typeof AppBoardRoute
  AppFilesRoute: typeof AppFilesRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppWebRoute: typeof AppWebRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBoardRoute: AppBoardRoute,
  AppFilesRoute: AppFilesRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppWebRoute: AppWebRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
